<a href="https://colab.research.google.com/github/anesairah/anes.airah/blob/main/Assignment4_A%C3%B1es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Añes, Airah Marie
Assignment 4

## Activity

## Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [2]:
def desc_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [22]:
C = np.array([
              [5,4,6],
              [3,5,1],
              [2,8,7]
])

K = np.array([
              [3,4,2],
              [7,9,6],
              [5,4,1]
])

M = np.array([])

ones_mat_row = np.ones((2,3))

E = np.eye(2,3)


In [23]:
desc_mat(C)

Matrix:
[[5 4 6]
 [3 5 1]
 [2 8 7]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [24]:
desc_mat(K)

Matrix:
[[3 4 2]
 [7 9 6]
 [5 4 1]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [25]:
desc_mat(M)

Matrix is Null


In [26]:
print(f'Ones Row Matrix: \n{ones_mat_row}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
desc_mat(E)

Matrix:
[[1. 0. 0.]
 [0. 1. 0.]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## Task2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared

In [29]:
def mat_operations(np,matA,matB):
  if matA.size > 0 or matB.size > 0:
    if matA.shape == matB.shape:
      if np == 'Add':
        sum = M1 + M2
        print(f'\nThe Sum of \n{matA} \n\n+\n\n {matB} \n\n is equal to:\n\n {sum}')
      if np == 'Subtract':
        sub = matA - matB
        print(f'\nThe Difference of \n{matA} \n\n-\n\n {matB} \n\n is equal to:\n\n {sub}')
      if np == 'Multiply':
        mul = matA * matB
        print(f'\nThe Product of \n{matA} \n\nx\n\n {matB} \n\n is equal to:\n\n {mul}')
      if np == 'Divide':
        div = matA / matB
        print(f'\nThe Result of \n{matA} \n\n/\n\n {matB} \n\n is equal to:\n\n {div}')
      else:
        print(f'Operation Not Found!')
    else:
      print(f'Syntax Error! Invalid Matrices detected.')
  else:
    print(f'One or Both the Matrix is NULL')