<a href="https://colab.research.google.com/github/anesairah/anes.airah/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Añes, Airah Marie
##**Assignment 6: Matrix Operations**

Now that Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.


##**Objectives**

At the end of this activity you will be able to:

1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.


##**Discussion**


In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Activity

## Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
G = np.array([
              [9,2,1],
              [2,0,5],
              [0,3,2]
])
A = np.array([
              [1,4,7],
              [4,8,6],
              [6,3,1]
])
B = np.array([
              [3,5,4],
              [7,3,8],
              [9,5,1]
])

$G \cdot A \neq A \cdot G$

In [9]:
np.dot(G,A)

array([[23, 55, 76],
       [32, 23, 19],
       [24, 30, 20]])

In [10]:
np.dot(A,G)

array([[17, 23, 35],
       [52, 26, 56],
       [60, 15, 23]])

$G \cdot (A \cdot B) = (G \cdot A) \cdot B$

In [16]:
X = np.dot(A,B)
Y = np.dot(G,A)
Z = np.dot(G,X)
W = np.dot(Y,B)

In [17]:
print(Q)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


In [18]:
print(Z)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


$G\cdot(A+B) = G\cdot A + G\cdot B$

In [19]:
D = A + G
print(D)

[[10  6  8]
 [ 6  8 11]
 [ 6  6  3]]


In [20]:
np.dot(G,D)

array([[108,  76,  97],
       [ 50,  42,  31],
       [ 30,  36,  39]])

In [22]:
E = np.dot(G,A)
print(E)

[[23 55 76]
 [32 23 19]
 [24 30 20]]


In [24]:
F = np.dot(G,B)
print(F)

[[50 56 53]
 [51 35 13]
 [39 19 26]]


In [25]:
D + F

array([[60, 62, 61],
       [57, 43, 24],
       [45, 25, 29]])

$(A+G)\cdot G = A\cdot G + B\cdot G$

In [26]:
np.dot((A+B),G)

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

In [28]:
S = np.dot(A,G)
L = np.dot(B,G)

In [29]:
S + L

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

$G\cdot I = G$

In [30]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(A)

[[1 4 7]
 [4 8 6]
 [6 3 1]]


In [32]:
np.dot(A,I)

array([[1., 4., 7.],
       [4., 8., 6.],
       [6., 3., 1.]])

$G\cdot \emptyset = \emptyset$

In [33]:
z_mat = np.zeros(G.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a_dot_z = G.dot(np.zeros(G.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.array_equal(a_dot_z,z_mat)

True

In [36]:
null_mat = np.empty(G.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Conclusion
We eventually understood the right usage of Python programming by practicing generating codes in Colaboratory while carrying out this experiment. This laboratory exercise seeks to put the ideas and practices of declaring and executing codes into reality, and Numpy is a useful package that allows you to quickly generate a matrix and perform matrix operations. In this laboratory activity, we were able to learn a lot about the source code element that featured matrix, which was important even though multiplier and all these other processes would become the basis of what we should perform as ECE students throughout future courses, and enhancing our computer program linguistic competence is an advantage for us students.
